import type { Deal } from "./prototype-deals"
import type { TradeFinanceFact } from "./erp-finance"

// Explicit demo records for the prototype's lifecycle and finance filters.
export const statusPreviewDeals: Deal[] = [
  {
    id: "DL-260918-91",
    title: "9월 철강재 거래 종결",
    counterparty: "ACME GmbH",
    primaryItem: "스테인리스 코일",
    itemCount: 1,
    orderLifecycle: "closed",
    stage: "settled",
    assignee: "조민영",
    amount: "50,820",
    currency: "USD",
    dday: "완료",
    eta: "2026.09.15",
    pending: 0,
    confirmed: 7,
    risks: [],
    nextWork: "finance",
    nextAction: "정산 완료",
    nextKind: "deliver",
  },
  {
    id: "DL-260918-92",
    title: "9월 운송 발주 취소",
    counterparty: "Sakura Logistics KK",
    primaryItem: "내륙운송",
    itemCount: 1,
    orderLifecycle: "cancelled",
    stage: "contract",
    assignee: "김도현",
    amount: "1,200,000",
    currency: "JPY",
    dday: "취소",
    eta: "2026.09.20",
    pending: 0,
    confirmed: 1,
    risks: [],
    nextWork: "documents",
    nextAction: "취소 내역 확인",
    nextKind: "confirm",
  },
  {
    id: "DL-260918-93",
    title: "거래 조건 확인 대기",
    counterparty: "Nordic Raw Materials AB",
    primaryItem: "산업용 원자재",
    itemCount: 1,
    stage: "contract",
    assignee: "미배정",
    amount: "24,000",
    currency: "EUR",
    dday: "미확인",
    eta: "2026.09.25",
    pending: 2,
    confirmed: 0,
    risks: ["amount"],
    nextWork: "documents",
    nextAction: "주문 조건 확인",
    nextKind: "confirm",
  },
]

export const statusPreviewFinance: Record<
  string,
  Array<Partial<TradeFinanceFact> & Pick<TradeFinanceFact, "currency">>
> = {
  "DL-260629-03": [
    {
      currency: "USD",
      revenue_amount: "1120000",
      goods_cost_amount: "1180000",
      receivable_current_target_amount: "1120000",
      receivable_applied_amount: "1000000",
      receivable_outstanding_amount: "120000",
      payable_current_target_amount: "1180000",
      payable_applied_amount: "900000",
      payable_outstanding_amount: "280000",
      data_quality: "confirmed",
      handoff_blockers: [],
      source_document_numbers: ["예시 CI-0918-S", "예시 CI-0918-P"],
    },
  ],
  "DL-260918-91": [
    {
      currency: "USD",
      revenue_amount: "50820",
      goods_cost_amount: "38400",
      receivable_current_target_amount: "50820",
      receivable_applied_amount: "50820",
      receivable_outstanding_amount: "0",
      payable_current_target_amount: "38400",
      payable_applied_amount: "38400",
      payable_outstanding_amount: "0",
      data_quality: "confirmed",
      handoff_blockers: [],
      source_document_numbers: ["예시 CI-0918-91"],
    },
  ],
}
